description: ''
keyword_arguments:
- name: help
  description: Show help options and exit
  shorthand: h
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: list
  description: Print all keys and their values
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: set
  description: Set key KEY to VALUE
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: unset
  description: Unset key KEY
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: get
  description: Print value of KEY
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: user
  description: Configure per-user installation
  shorthand: u
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: system
  description: Configure system-wide installation
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: installation
  description: Configure the system-wide installation specified by NAME among those defined …
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: verbose
  description: Print debug information during command processing
  shorthand: v
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: ostree-verbose
  description: Print OSTree debug information during command processing
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
