description: ''
keyword_arguments:
- name: host
  description: Get per-host setting EXAMPLE $ gh config get git_protocol https SEE ALSO
  shorthand: h
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
