description: ''
keyword_arguments:
- name: output
  description: output generated config to FILE [default=stdout]
  shorthand: o
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: help
  description: print this message and exit
  shorthand: h
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: print the version information and exit REPORTING BUGS Report bugs to <bug-gru…
  shorthand: V
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
