description: ''
keyword_arguments:
- name: nostdlib
  description: Do not search the system default gconv directory, only the directories provid…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: output
  description: Use  outputfile for output instead of the system default cache location
  shorthand: o
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: prefix
  description: Set the prefix to be prepended to the system pathnames.  See FILES, below
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: help
  description: Print a usage summary and exit
  shorthand: '?'
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: usage
  description: Print a short usage summary and exit
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: 'Print the version number, license, and disclaimer of warranty for iconv '
  shorthand: V
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
