description: ''
keyword_arguments:
- name: version
  description: Print the currently installed version of libmikmod on the standard output
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs
  description: Print the linker flags that are necessary to link a libmikmod program
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: ldadd
  description: Print the extra linker flags that are necessary to link a libmikmod program i…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cflags
  description: Print the compiler flags that are necessary to compile a libmikmod program
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: prefix
  description: If specified, use PREFIX instead of the installation prefix that libmikmod wa…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-prefix
  description: If specified, use PREFIX instead of the installation exec prefix that libmikm…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
