description: ''
keyword_arguments:
- name: assertion-mode
  description: Print the assertion mode used when LLVM was built (ON or OFF)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: bindir
  description: Print the installation directory for LLVM binaries
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: build-mode
  description: Print the build mode used when LLVM was built (e. g.  Debug or Release)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: build-system
  description: Print the build system used to build LLVM (e. g.  cmake or gn)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cflags
  description: Print the C compiler flags needed to use LLVM headers
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cmakedir
  description: Print the installation directory for LLVM CMake modules
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: components
  description: Print all valid component names
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cppflags
  description: Print the C preprocessor flags needed to use LLVM headers
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cxxflags
  description: Print the C++ compiler flags needed to use LLVM headers
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: has-rtti
  description: Print whether or not LLVM was built with rtti (YES or NO)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: help
  description: Print a summary of llvm-config arguments
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: host-target
  description: Print the target triple used to configure LLVM
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: ignore-libllvm
  description: Ignore libLLVM and link component libraries instead
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: includedir
  description: Print the installation directory for LLVM headers
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: ldflags
  description: Print the flags needed to link against LLVM libraries
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libdir
  description: Print the installation directory for LLVM libraries
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libfiles
  description: Similar to --libs, but print the full path to each library file
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libnames
  description: Similar to --libs, but prints the bare filenames of the libraries without -l …
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs
  description: Print all the libraries needed to link against the specified LLVM components,…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: link-shared
  description: Link the components as shared libraries
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: link-static
  description: Link the component libraries statically
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: obj-root
  description: Print the object root used to build LLVM
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: prefix
  description: Print the installation prefix for LLVM
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: shared-mode
  description: Print how the provided components can be collectively linked (shared or stati…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: src-root
  description: Print the source root from which LLVM was built
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: system-libs
  description: Print all the system libraries needed to link against the specified LLVM comp…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: targets-built
  description: Print the component names for all targets supported by this copy of LLVM
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: Print the version number of LLVM.  COMPONENTS
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
