description: ''
keyword_arguments:
- name: os
  description: Use a different operating system stateroot than the current one
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
