description: ''
keyword_arguments:
- name: prefix
  description: Writes the directory prefix used in the PCRE2 installation for architecture i…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-prefix
  description: Writes the directory prefix used in the PCRE2 installation for architecture d…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: Writes the version number of the installed PCRE2 libraries to the standard ou…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs8
  description: Writes to the standard output the command line options required to link with …
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs16
  description: Writes to the standard output the command line options required to link with …
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs32
  description: Writes to the standard output the command line options required to link with …
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs-posix
  description: Writes to the standard output the command line options required to link with …
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cflags
  description: Writes to the standard output the command line options required to compile fi…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cflags-posix
  description: Writes to the standard output the command line options required to compile fi…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: I
  description: SEE ALSO pcre2(3) AUTHOR This manual page was originally written by Mark Bake…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
