description: ''
keyword_arguments:
- name: help
  description: Display a short usage message
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: Display the version of the applet
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: debug
  description: Show debugging information
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: no-tray-icon
  description: 'option: a desktop file is provided for this, so that it should appear in the …'
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
