description: ''
keyword_arguments:
- name: help
  description: Display a short usage message
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: show-jobs
  description: Show the named print queue
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: debug
  description: Enable debugging output
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
