description: ''
keyword_arguments:
- name: P
  description: option is given
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: O
  description: option in dvips(1)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
