description: ''
keyword_arguments:
- name: cflags
  description: Print the compiler flags that are necessary to compile a program or library t…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-prefix
  description: If specified, use  DIR instead of the installation exec prefix that libcaca w…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs
  description: Print the linker flags that are necessary to link a program or library that u…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: prefix
  description: If specified, use PREFIX instead of the installation prefix that libcaca was …
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: Prints the currently installed version of libcaca on standard output
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
