description: ''
keyword_arguments:
- name: compose-file
  description: "\tPath to a Compose file, or \"-\" to read from stdin"
  shorthand: c
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: help
  description: "\thelp for config"
  shorthand: h
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: skip-interpolation
  description: "\tSkip interpolation and output only merged config SEE ALSO"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
