description: ''
keyword_arguments:
- name: n
  description: Configure this print queue
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: N
  description: Use this proper human-readable name/description
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: L
  description: Short phrase describing this printer\'s location
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: c
  description: Printer is connected thusly (ex file:/dev/lp0)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: d
  description: Foomatic database name for desired printer driver
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: p
  description: Foomatic id for printer
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: ppd
  description: PPD file, for example the one supplied by the manufacturer of a PostScript pr…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: s
  description: Explicit spooler type (cups, lpd, lprng, pdq, ppr, direct)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: o
  description: Set the default of option to value
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: D
  description: Set this queue as the default queue (just give -n queuename)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: R
  description: Remove this whole queue entirely (just give -n queuename)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: C
  description: Copy sourcequeue from sourcespooler (or the current one if sourcespooler is n…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: Q
  description: Query existing configuration (gives XML summary)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: r
  description: List also remotely defined queues (CUPS only)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: P
  description: Get Perl dump of current configuration (as a Perl array named QUEUES, the fir…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: O
  description: Print XML Overview of all known printer/drivers (this shows also the Foomatic…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: X
  description: Print XML data for -p printer and/or -d driver object
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: q
  description: Run quietly Commands No commands, just options SEE ALSO foomatic-printjob (1)…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
