description: ''
keyword_arguments:
- name: host
  description: Set per-host setting EXAMPLE $ gh config set editor vim $ gh config set edito…
  shorthand: h
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
