description: ''
keyword_arguments:
- name: expandvars
  description: Expand ${prefix} and ${exec_prefix} in output
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: prefix
  description: Compiled in prefix for Frameworks libraries
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-prefix
  description: Compiled in exec_prefix for Frameworks libraries
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libsuffix
  description: Compiled in library path suffix
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: localprefix
  description: Prefix in $HOME used to write files
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: Version of Qt(TM) and compiled in version string for Frameworks libraries and…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: kde-version
  description: Compiled in version string for Frameworks libraries
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: types
  description: Print a list of all available KDE resource types
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: path
  description: Search path for the specified type
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: userpath
  description: 'User paths for the types: desktop|document'
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: install
  description: Prefix to install resource files to
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: qt-prefix
  description: Installation prefix for Qt(TM)
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: qt-binaries
  description: Location of installed Qt(TM) binaries
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: qt-libraries
  description: Location of installed Qt(TM) libraries
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: qt-plugins
  description: Location of installed Qt(TM) plugins
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
