description: ''
keyword_arguments:
- name: auth-provider
  description: "\tAuth provider for the user entry in kubeconfig"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: auth-provider-arg
  description: "\t\\'key=value\\' arguments for the auth provider"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: client-certificate
  description: "\tPath to client-certificate file for the user entry in kubeconfig"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: client-key
  description: "\tPath to client-key file for the user entry in kubeconfig"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: embed-certs
  description: "\tEmbed client cert/key for the user entry in kubeconfig"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-api-version
  description: "\tAPI version of the exec credential plugin for the user entry in kubeconfig"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-arg
  description: "\tNew arguments for the exec credential plugin command for the user entry in k…"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-command
  description: "\tCommand for the exec credential plugin for the user entry in kubeconfig"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-env
  description: "\t\\'key=value\\' environment values for the exec credential plugin"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: password
  description: "\tpassword for the user entry in kubeconfig"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: token
  description: "\ttoken for the user entry in kubeconfig"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: username
  description: "\tusername for the user entry in kubeconfig OPTIONS INHERITED FROM PARENT COMM…"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: as
  description: "\tUsername to impersonate for the operation"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: as-group
  description: "\tGroup to impersonate for the operation, this flag can be repeated to specify…"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: as-uid
  description: "\tUID to impersonate for the operation"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: azure-container-registry-config
  description: "\tPath to the file containing Azure container registry configuration informati…"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cache-dir
  description: "\tDefault cache directory"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: certificate-authority
  description: "\tPath to a cert file for the certificate authority"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cluster
  description: "\tThe name of the kubeconfig cluster to use"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: context
  description: "\tThe name of the kubeconfig context to use"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: disable-compression
  description: "\tIf true, opt-out of response compression for all requests to the server"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: insecure-skip-tls-verify
  description: "\tIf true, the server\\'s certificate will not be checked for validity"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: kubeconfig
  description: "\tuse a particular kubeconfig file"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: match-server-version
  description: "\tRequire server version to match client version"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: namespace
  description: "\tIf present, the namespace scope for this CLI request"
  shorthand: n
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: profile
  description: "\tName of profile to capture"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: profile-output
  description: "\tName of the file to write the profile to"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: request-timeout
  description: "\tThe length of time to wait before giving up on a single server request"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: server
  description: "\tThe address and port of the Kubernetes API server"
  shorthand: s
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: tls-server-name
  description: "\tServer name to use for server certificate validation"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: user
  description: "\tThe name of the kubeconfig user to use"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: "\tPrint version information and quit"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: warnings-as-errors
  description: "\tTreat warnings received from the server as errors and exit with a non-zero e…"
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
