description: ''
keyword_arguments:
- name: cflags
  description: Show the C compiler flags needed to compile with ldns
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs
  description: Show the flags to be used to link with ldns
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: Shows the ldns version of the installed ldns library
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libversion
  description: Shows version of the binary api of the installed ldns library
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: help
  description: Show ldns-config usage description
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
