description: ''
keyword_arguments:
- name: cflags
  description: 'Print the compiler flags that were used to compile   libWand '
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cppflags
  description: Print the preprocessor flags that are needed to find the  Wand C include file…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-prefix
  description: Print the directory under which target specific binaries and executables are …
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: ldflags
  description: Print the linker flags that are needed to link with the  Wand library
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs
  description: 'Print the linker flags that are needed to link a program with  libWand '
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: Print the version of the Wand distribution to standard output
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
