description: ''
keyword_arguments:
- name: cflags
  description: Print the flags which should be passed to the C compiler when compiling objec…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs
  description: Print the flags which should be passed to the linker when linking an applicat…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: la-file
  description: Print the location of the libtool library script, libneon
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: Print the version of the library
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: prefix
  description: If dir is given; relocate output of --cflags and --libs as if neon was instal…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: support
  description: The script exits with success if feature is supported by the library
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: help
  description: Print help message; includes list of known features and whether they are supp…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
