description: ''
keyword_arguments:
- name: editor
  description: Editor to use to edit the file
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: global
  description: Use the system-wide configuration file only
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: user
  description: Use the user configuration file only
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: site
  description: Use the current environment configuration file only
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
