description: ''
keyword_arguments:
- name: version
  description: Print the currently installed version of redland on the standard output
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version-decimal
  description: Print the currently installed version of redland as a decimal integer
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs
  description: Print the linker flags that are necessary to link a redland program
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libtool-libs
  description: Print the flags that are necessary to link a redland program with libtool
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: private-libs
  description: Print the linker flags that are necessary to build the librdf shared library
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: cflags
  description: Print the compiler flags that are necessary to compile a redland program
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: prefix
  description: If specified, use PREFIX instead of the installation prefix that redland was …
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
