description: ''
keyword_arguments:
- name: cxxflags
  description: output all preprocessor and C++ compiler flags
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs
  description: output all linker flags
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: ltlibs
  description: output linker flags for linking using GNU libtool
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: static
  description: make other options report values for static linking
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: swigflags
  description: output preprocessor flags for use with SWIG
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: help
  description: output this help and exit
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: output version information and exit REPORTING BUGS Report bugs to <https://xa…
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
