description: ''
keyword_arguments:
- name: cflags
  description: print pre-processor and compiler flags
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libs
  description: print library linking information
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: prefix
  description: print the default XMLSEC prefix folder
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: exec-prefix
  description: print the default XMLSEC executable prefix folder
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: libdir
  description: print the default XMLSEC libraries folder
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: crypto
  description: print the default crypto library name
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: help
  description: display this help and exit
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
- name: version
  description: output version information
  shorthand: null
  repeatable: false
  arg_type:
    type: String
  incompatible_with: []
positional_arguments: []
arguments_valid_anywhere: true
